language: cpp
cache:
 ccache: true
 directories:
    - /home/travis/toolchain

matrix:
  include:

  # Ubuntu, g++-8
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        sources:
          - sourceline: 'ppa:mhier/libboost-latest'
          - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - libssl-dev
          - g++-8
          - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Ubuntu, g++-7
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        sources:
          - sourceline: 'ppa:mhier/libboost-latest'
          - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - libssl-dev
          - g++-7
          - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"

  # Arm (aarch64) cross compile
  - os: linux
    dist: bionic
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

script:
- eval $MATRIX_EVAL
# If we're cross compiling aarch64, make sure our build enivornment is setup
# we do this in the script stage because this happens after the repo is cloned
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- ${STRIP} Xenium*
- rm -rf Xenium-${TRAVIS_TAG}
- mkdir Xenium-${TRAVIS_TAG}
- cp Xenium* Xenium-${TRAVIS_TAG}/
- cp ../../LICENSE Xenium-${TRAVIS_TAG}/
- tar cvfz Xenium-${TRAVIS_TAG}-${LABEL}.tar.gz Xenium-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp Xenium-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd ..

deploy:
  - provider: releases
    api_key:
      secure: inj/QyKx2LQcFjIwmQOqdeD1+PrlJAkigKK4qVAxvrbpHEpqLuBV6Gdl7vIFgVp6AwPrD5EZSSWIV4Jm7/fIC8YRtgnP9WaNnlFDuWkfZgv+BZJpf/TQbPUSefRLS/pr4Sf2rjVr/M6WA2dXQA7FwksK8dAayzqJOmWdUxMn/azrBXNfsX4Rb9FaN1aa4vifWjWzJmwMoFvdo5VVdq9BRzvcaXFG3yMVxAI0c6BsAejNkqnC6LiA2vGlRTmjtlbUKFSlqDUWz3edE6lbzkaDBKCbqCLxFD4N7vS8fedKPhf2ppJSNFGcJSO2UVzNj0aTtxyKzwPnaroLxHgtspLefJHWy6NCmkEpkHFE8DyVZcAgUA8S/FGzySeQp65qghBD1m0dc7ImwUWtiIB6JE23OeJAc162ikUXQPE6ZtY9Vxo/CR2WBB4U+Z/tzC+XV8q33STNJw1/pyahu4y3+ZfOCLz+wA3+3GfC1H5F+Z61pytZdKM4sIFJs+iy/YjjsAW9XRv1IVorvd0s22nzMWtfh8zNUPGAR83TInrPa3e3ADUXuZuKS67VRHEE8VWPgNHPoMtok39E95j2exTh+F94hrQF6r7ttuU5UiXzMqcmG3AiU+0yWl9NON7NXNvDN/wOwQUD2SU8+/Gl1eZtKLk6JDMnV1pjUck4mB3RioVluJU=
    file:
      - Xenium-${TRAVIS_TAG}-${LABEL}.tar.gz
    skip_cleanup: true
    on:
      repo: xenium-project/xenium
      tags: true
      condition: "$_DEPLOYABLE = true"
